001 view job roles
ntotten-kainos/Agile-T2-Frontend pull request #12
Opened 2024-07-24 13:28 UTC by mark-mcilroykainos

2024-07-24 14:13 UTC, mark-mcilroykainos commented
Hopefully sorted merge conflicts and branch is ready to be merged with main..

2024-07-25 08:19 UTC, ntotten-kainos submitted a review, later dismissed
LGTM : Just whitespaces might get caught by linter

2024-07-25 08:19 UTC, ntotten-kainos commented on test/unit/services/JobRoleServiceTest.ts
> +
Super nit: whitespaces

2024-07-25 08:30 UTC, shaunganley requested changes
please add the coverage folder to your git ignore and delete them from here

2024-07-25 08:30 UTC, shaunganley commented on src/services/JobRoleService.ts
> +        const response: AxiosResponse = await axios.get("http://localhost:8080/api/job-roles"); // will need amended
this will work locally but not on AWS, please pass the base API URL in as an environment variable

2024-07-25 09:13 UTC, shaunganley approved these changes

2024-07-25 09:26 UTC, ntotten-kainos approved these changes

2024-07-25 09:26 UTC, ntotten-kainos commented
LGTM

2024-07-25 09:27 UTC, merged